### ISSUE TITLE
iOS 15.x Rootless support

### ISSUE THREAD

**Issue by lonkelle** [HearseDev/3developer#2]
This was one of my fav tweaks back in the 14.x days and it’d be dope if it got a new rootless iOS 15.x update. I miss it.

**Comment by HearseDev** [comment]
Hi Ionkelle, this tweak has been updated with minor fixes and rootless support. 

You are able to compile it with this command `make clean package -j8 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless`

**Comment by HearseDev** [comment]
> This was one of my fav tweaks back in the 14.x days and it’d be dope if it got a new rootless iOS 15.x update. I miss it.

This tweak has been updated with minor fixes and rootless support. 
You are able to compile it with this command `make clean package -j8 FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless`
